CREATE TABLE IF NOT EXISTS metric_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clientname VARCHAR(128) NOT NULL,
    sort_key VARCHAR(192) NOT NULL,
    event_timestamp VARCHAR(64) NOT NULL,
    metric VARCHAR(128) NOT NULL,
    action VARCHAR(128) NOT NULL,
    event_id UUID NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    source_ip INET NOT NULL,
    CONSTRAINT uq_metric_events_event_id UNIQUE (event_id)
);

CREATE INDEX IF NOT EXISTS idx_metric_events_client_sort
    ON metric_events (clientname, sort_key);

CREATE INDEX IF NOT EXISTS idx_metric_events_received_at
    ON metric_events (received_at);
